# Generated by Django 5.2.5 on 2025-08-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
